site_name: Jason Greymane (Gaekwad)
site_url: https://github.com/JGaekwad/bio_page
nav:
  - Home: index.md

theme:
  name: landing

  favicon: "assets/favicon.png"

  avatar: assets/avatar.png
  avatar_size: 10rem
  round_avatar: false

  tagline: |
    Curious mind, grounded practice
  footer: |
      Compiled from markdown using [MkDocs](https://www.mkdocs.org/), hosted via [GitHub Pages](https://pages.github.com/). Theme by [Todd Parsons](https://toddparsons.co.uk).
  socials:
    - label: Email
      link: mailto:humanenvironments@deakin.edu.au
      icon: at
    - label: LinkedIn
      link: https://au.linkedin.com/in/jasongaekwad
      icon: [brands, linkedin]
    - label: ResearchGate
      link: https://www.researchgate.net/profile/Jason-Gaekwad-2
      icon: [brands, researchgate]
    - label: GitHub
      link: https://github.com/JGaekwad
      icon: [brands, github]
    - label: ORCiD
      link: https://orcid.org/0000-0003-0273-9370
      icon: [brands, orcid]
